spring:
  application:
    name: delivery
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: username
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
