spring:
  application:
    name: delivery
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: username
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


grpc:
  client:
    geo:
      address: localhost:9090
      negotiation-type: plaintext